sync:
	uv sync
	
installme:
	uv pip install -e .

test:
	uv run pytest -s tests/ --cov={{project_name}}

docs:
	uv run mkdocs build

docs_serve:
	uv run mkdocs serve

.PHONY: sync test installme docs docs_serve

