[tool.uv]
name = "{{ project_name }}"
version = "0.1.0"
description = "A minimal Python package"
authors = ["{{ author_name }}"]
license = "{{ license }}"
readme = "README.md"
python = ">=3.6"
dependencies = []

[tool.uv.scripts]
# Define any CLI scripts here
